name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Generate Deployment Package
        run: |
          # Create a zip containing the app files and the Docker configuration
          zip -r deploy.zip . -x "*.git*" "node_modules/*" ".github_pat" ".env" "deploy.zip"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}
          application_name: Teachures
          environment_name: Teachures-env
          version_label: "Teachures-${{ github.sha }}"
          deployment_package: deploy.zip
          use_existing_version_if_available: true
